openapi: 3.1.0

info:
  title: Emulated device property pattern models
  version: ^0.0.0
  x-pattern: 
    description: >-
      This object MUST be used to provide additional information about the
      child pattern.
    format: 
    - ipv4
    - ipv6
    - hex
    - mac
    - integer
    - number
    - enum
    enums: A list of enums that the pattern is constrained to
    default: Default value of the pattern value

components:
  schemas:
    Pattern.IntegerCounter:
      description: >-
        An integer counter pattern.
      type: object
      required: ['start', 'step']
      properties:
        start:
          type: integer
        step:
          type: integer

    Pattern.NumberCounter:
      description: >-
        A number counter pattern.
      type: object
      required: ['start', 'step']
      properties:
        start:
          type: number
        step:
          type: number
