openapi: 3.1.0

info:
  title: Emulated device property pattern models
  version: ^0.0.0
  x-pattern: 
    description: >-
      This object MUST be used to provide additional information about the
      child pattern.
    format: 
    - ipv4
    - ipv6
    - hex
    - mac
    - integer
    - number
    - enum
    enums: A list of enums that the pattern is constrained to
    default: Default value of the pattern value

components:
  schemas:
    Device.Pattern:
      description: >-
        A container for emulated device property patterns.
      type: object
      required: [choice]
      properties:
        choice: 
          type: string
          enum: [value, values, increment, decrement]
        value:
          type: string
        values:
          type: array
          items:
            type: string
        increment:
          $ref: '#/components/schemas/Device.Counter'
        decrement:
          $ref: '#/components/schemas/Device.Counter'

    Device.Counter:
      description: >-
        An incrementing pattern.
      type: object
      properties:
        start:
          type: string
        step:
          type: string

    Device.EnumPattern:
      description: >-
        A container for emulated device property enum patterns.
        Only value or values is allowed.
      type: object
      required: [choice]
      properties:
        choice: 
          type: string
          enum: [value, values]
        value:
          type: string
        values:
          type: array
          items:
            type: string

    Device.BoolPattern:
      description: >-
        A container for emulated device property boolean patterns.
        Only value or values is allowed.
      type: object
      required: [choice]
      properties:
        choice: 
          type: string
          enum: [value, values]
        value:
          type: boolean
        values:
          type: array
          items:
            type: boolean
